name: Frontend Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ------------------------
      # 构建 frontend-user
      # ------------------------
      - name: Install dependencies (frontend-user)
        working-directory: ${{ github.workspace }}/frontend-user
        run: npm install --registry=https://registry.npmmirror.com

      - name: Build project (frontend-user)
        working-directory: ${{ github.workspace }}/frontend-user
        run: npm run build

      - name: Upload frontend-user to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # 使用 GitHub Secrets 中的私钥
          port: 22
          source: "${{ github.workspace }}/frontend-user/dist/*"
          target: "/var/www/html/user"  # 修改为与 Nginx 配置一致的路径

      # ------------------------
      # 构建 frontend-admin
      # ------------------------
      - name: Install dependencies (frontend-admin)
        working-directory: ${{ github.workspace }}/frontend-admin
        run: npm install --registry=https://registry.npmmirror.com

      - name: Build project (frontend-admin)
        working-directory: ${{ github.workspace }}/frontend-admin
        run: npm run build

      - name: Upload frontend-admin to server
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # 使用 GitHub Secrets 中的私钥
          port: 22
          source: "${{ github.workspace }}/frontend-admin/dist/*"
          target: "/var/www/html/admin"  # 修改为与 Nginx 配置一致的路径
